// Generated by CoffeeScript 1.6.3
(function() {
  var advanced, filterBox, search, slider;

  $(document).ready(function() {
    return $('select').select2();
  });

  $(function() {
    return $("#freeform").select2({
      tags: [],
      tokenSeparators: [",", " "]
    });
  });

  $(function() {
    $("#category-values1, #category-values2, #category-values3").select2({
      placeholder: "Available Options"
    });
    return $("#category-selector1, #category-selector2, #category-selector3").select2({
      placeholder: "Available Categories",
      allowClear: true
    });
  });

  advanced = true;

  $(function() {
    return $(".advancedToggle").on("click", function() {
      if (advanced) {
        $(".advanced").slideDown(300);
      } else {
        $(".advanced").slideUp(300);
      }
      return advanced = !advanced;
    });
  });

  $(function() {
    return $('#add-line').click(function() {
      return $('.edit').css("display", "block");
    });
  });

  $(function() {
    return $('#add-line-close, #add-line-close2').click(function() {
      return $('.edit').css("display", "none");
    });
  });

  $(document).ready(function() {
    return $('.help-command > a').click(function() {
      if ($('.help-menu').toggleClass('hidden')) {
        return $('.help-search').focus();
      }
    });
  });

  $(document).ready(function() {
    return $(".side-menu").sidr({
      speed: 75
    });
  });

  slider = true;

  $(function() {
    return $(".side-menu").on("click", function() {
      if (slider) {
        $(".side-menu i").css("color", "#999");
      } else {
        $(".side-menu i").css("color", "#fff");
      }
      return slider = !slider;
    });
  });

  search = true;

  $(function() {
    return $("#global-search, .global-search li a").on("click", function() {
      if (search) {
        $(".global-search").css("display", "block");
      } else {
        $(".global-search").css("display", "none");
      }
      return search = !search;
    });
  });

  filterBox = true;

  $(function() {
    return $("#filter-box, .close-box").on("click", function() {
      if (filterBox) {
        $(".filter-box").css("display", "block");
      } else {
        $(".filter-box").css("display", "none");
      }
      return filterBox = !filterBox;
    });
  });

  $(function() {
    return $(".close").click(function() {
      return $("#notifications").fadeOut(250);
    });
  });

  $(function() {
    return $("#freeform-tags").select2({
      tags: [],
      tokenSeparators: [",", " "]
    });
  });

  $(document).ready(function() {
    return $(document.body).removeClass('loading');
  });

}).call(this);
